language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- echo -e "Host $DIST_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
deploy:
- provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-multi-release-tile
- provider: script
  skip_cleanup: true
  script: rsync --update -raz -i $TRAVIS_BUILD_DIR/build/libs/*.jar $DIST_USER@$DIST_HOST:$DIST_PATH/${TRAVIS_REPO_SLUG#*/}/
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-multi-release-tile
