language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- echo -e "Host $DIST_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- chmod +x gradlew
deploy:
- provider: releases
  api_key:
    secure: vFU4Sm7Q7luHgvO7E7fi5eD0mhUs3fHpYboyAN8qQ6ROn1ogHIcg1sBo5s9CWAhHlxW5CxCWY2E7L2ahX0waI8ZHEcrITOusk0LC+cK52Y/GAPbBS/5roPET4wrk4BfKPa66ePgfsygHBw35P9xIHiFuKPA3QjFdSsdtBMYVYhmjGDjDfdYXLSwqBTpoA3EcBCEDfLAUWGRahfjOZOlOZUmN1oD8cAgoQ2uVpuv0ZcY9UOX657BA0+CqOj92+VQSo3Ms7CEB56gSDi8S1YYzi4TNDsOFg2Z7zQwBmtbxYl0JVsWjYiuKviHNpfvYkC+BSwfvZAUBuUHTvBRfI5uaXmj+rEeWriEUACmiTubYSWSDd0TpSFTM5HS7L2xFDpVDUljZIgzybMlUq9uPRw4rfhc94jaN3yjr9ikO1O68Jyy0iF8HbX4oCYpmmg+TNFwNYQdL5IRtN6d4oZnszMQ6Omstqd4uGhQGp/w66XZ6dkZObe8ASjRfTuNVzFYBR5klS+D1+twWLRyVk+fK8uHPdFGswVO6lVmqqoDl7Cp6k/L4GVfYbulOWXJo70JFyfRhOamM0f3ECf1Ine2zO3AbTEf8r3xUmUrqEZ0j4rWg6QvQ2rt7nVYR/1Oq/BoZqdAt+Plfch+HG8v2sCu/FV8T30GBjCocDqzpmKANCPXJaXI=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-multi-release-tile
- provider: script
  skip_cleanup: true
  script: rsync --update -raz -i $TRAVIS_BUILD_DIR/build/libs/*.jar $DIST_USER@$DIST_HOST:$DIST_PATH/${TRAVIS_REPO_SLUG#*/}/
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-multi-release-tile
