name: Java CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SCM checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Repository Name
        run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        shell: bash
      - name: Set Tag Name
        run: echo ::set-env name=TAG::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Gradle
        run: ./gradlew clean assemble
      - name: Create Release in GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: join(['build/libs/',${REPOSITORY_NAME},-,${TAG},'.jar'])
          asset_name: "${REPOSITORY_NAME}"-"${TAG}".jar
          asset_content_type: application/jar