name: Java CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: SCM checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Gradle
        run: ./gradlew clean assemble
      - name: deploy
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./build/libs/xlr-multi-release-tile*.*
      - name: deploy to dist
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SOURCE: "./build/libs/xlr-multi-release-tile*.*"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.REMOTE }}