name: Java CI

on:
  push:
    branches:
      - karthik
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew clean assemble
